/**
 * Seed Master Preset Frames
 * @param {import('@prisma/client').PrismaClient} prisma
 */
export async function seedFrames(prisma) {
  console.log('🖼️ Seeding Master PNG Frames with configJson Vector Blueprints...');

  const masterFrames = [
    {
      id: 'frame-gold-border-png',
      title: 'Gold Luxury Border Frame',
      description: 'Elegant golden transparent border overlay suitable for premium business posts.',
      overlayPngUrl: 'https://res.cloudinary.com/dksdc3q6y/image/upload/v1711111111/brandflow/frames/gold_luxury_frame.png',
      isSystem: true,
      isActive: true,
      configJson: {
        elements: [
          {
            id: 'shape_gold_bar',
            type: 'CAPSULE',
            slotCategory: 'STATIC_SHAPE',
            x: 140,
            y: 920,
            width: 800,
            height: 120,
            fillColor: '#EAB308',
            borderColor: '#FFFFFF',
            borderWidth: 3,
          },
          {
            id: 'avatar_gold_circle',
            type: 'CIRCLE',
            slotCategory: 'IMAGE_SLOT',
            dynamicSlot: 'AVATAR_CIRCLE',
            customLabel: 'Profile Headshot Photo',
            x: 160,
            y: 930,
            width: 100,
            height: 100,
            borderColor: '#EAB308',
            borderWidth: 4,
          },
          {
            id: 'logo_gold_box',
            type: 'RECTANGLE',
            slotCategory: 'IMAGE_SLOT',
            dynamicSlot: 'LOGO_BOX',
            customLabel: 'Business Logo Box',
            x: 40,
            y: 40,
            width: 140,
            height: 60,
            fillColor: '#0B0F17',
            borderColor: '#EAB308',
            borderWidth: 2,
          },
          {
            id: 'text_gold_biz_name',
            type: 'TEXT',
            slotCategory: 'TEXT_INPUT',
            dynamicSlot: 'BUSINESS_NAME',
            customLabel: 'Business Name',
            fieldKey: 'businessName',
            text: 'Sunrise Real Estate',
            x: 280,
            y: 940,
            width: 600,
            height: 40,
            fontSize: 26,
            fontFamily: 'Space Grotesk',
            fontWeight: 'bold',
            fontColor: '#FFFFFF',
            textAlign: 'left',
          },
          {
            id: 'text_gold_phone',
            type: 'TEXT',
            slotCategory: 'TEXT_INPUT',
            dynamicSlot: 'PHONE',
            customLabel: 'Phone / WhatsApp',
            fieldKey: 'phone',
            iconPrefix: '📞',
            text: '+91 98765 43210',
            x: 280,
            y: 980,
            width: 600,
            height: 35,
            fontSize: 20,
            fontFamily: 'Space Grotesk',
            fontWeight: 'bold',
            fontColor: '#FEF08A',
            textAlign: 'left',
          },
        ],
      },
    },
    {
      id: 'frame-classic-corporate-png',
      title: 'Classic Corporate Minimal Overlay',
      description: 'Clean transparent footer and corner badge overlay for business announcements.',
      overlayPngUrl: 'https://res.cloudinary.com/dksdc3q6y/image/upload/v1711111111/brandflow/frames/corporate_minimal_frame.png',
      isSystem: true,
      isActive: true,
      configJson: {
        elements: [
          {
            id: 'shape_corp_line',
            type: 'RECTANGLE',
            slotCategory: 'STATIC_SHAPE',
            x: 0,
            y: 936,
            width: 1080,
            height: 4,
            fillColor: '#38BDF8',
          },
          {
            id: 'shape_corp_footer',
            type: 'RECTANGLE',
            slotCategory: 'STATIC_SHAPE',
            x: 0,
            y: 940,
            width: 1080,
            height: 140,
            fillColor: '#0F172A',
            borderColor: '#38BDF8',
            borderWidth: 1,
          },
          {
            id: 'avatar_corp_circle',
            type: 'CIRCLE',
            slotCategory: 'IMAGE_SLOT',
            dynamicSlot: 'AVATAR_CIRCLE',
            customLabel: 'Owner Profile Photo',
            x: 40,
            y: 955,
            width: 110,
            height: 110,
            borderColor: '#38BDF8',
            borderWidth: 3,
          },
          {
            id: 'text_corp_biz_name',
            type: 'TEXT',
            slotCategory: 'TEXT_INPUT',
            dynamicSlot: 'BUSINESS_NAME',
            customLabel: 'Company Name',
            fieldKey: 'businessName',
            text: 'Apex Financial Services',
            x: 180,
            y: 960,
            width: 500,
            height: 40,
            fontSize: 28,
            fontFamily: 'Space Grotesk',
            fontWeight: 'bold',
            fontColor: '#FFFFFF',
            textAlign: 'left',
          },
          {
            id: 'text_corp_phone',
            type: 'TEXT',
            slotCategory: 'TEXT_INPUT',
            dynamicSlot: 'PHONE',
            customLabel: 'Contact Phone',
            fieldKey: 'phone',
            iconPrefix: '📞',
            text: '+91 99999 88888',
            x: 180,
            y: 1005,
            width: 400,
            height: 35,
            fontSize: 20,
            fontFamily: 'Space Grotesk',
            fontWeight: 'bold',
            fontColor: '#38BDF8',
            textAlign: 'left',
          },
          {
            id: 'text_corp_address',
            type: 'TEXT',
            slotCategory: 'TEXT_INPUT',
            dynamicSlot: 'ADDRESS',
            customLabel: 'Office Address',
            fieldKey: 'address',
            iconPrefix: '📍',
            text: 'Financial District, Mumbai',
            x: 600,
            y: 1005,
            width: 440,
            height: 35,
            fontSize: 20,
            fontFamily: 'Space Grotesk',
            fontWeight: 'bold',
            fontColor: '#94A3B8',
            textAlign: 'left',
          },
        ],
      },
    },
  ];

  for (const frame of masterFrames) {
    await prisma.frame.upsert({
      where: { id: frame.id },
      update: frame,
      create: frame,
    });
  }

  console.log('✅ Master PNG Frames seeded with configJson schemas.');
}
