import {
  AI_SOURCES,
  DEFAULT_FALLBACK_HASHTAGS,
} from './ai.constants.js';

/**
 * 🤖 AI DATA SANITIZER & HELPER
 * Strict data minimization projections and prompt engineering helpers for AI copywriting.
 */

/**
 * Sanitize caption response object (OWASP Data Minimization)
 * Strips all internal tokens, debug parameters, and unneeded LLM payloads.
 *
 * @param {Object} data
 * @param {string} data.source - Generation source (GEMINI_AI | OPENAI | SMART_SYNTHESIZER)
 * @param {string} data.captionText - Clean formatted caption string
 * @param {Array<string>} data.hashtags - Array of relevant hashtag strings
 * @returns {{ source: string, captionText: string, hashtags: Array<string> }}
 */
export function sanitizeCaptionResponse({ source, captionText, hashtags }) {
  return {
    source: source || AI_SOURCES.SMART_SYNTHESIZER,
    captionText: typeof captionText === 'string' ? captionText.trim() : '',
    hashtags: Array.isArray(hashtags) && hashtags.length > 0 ? hashtags : [...DEFAULT_FALLBACK_HASHTAGS],
  };
}


/**
 * 🏷️ EXTRACT HASHTAG TOKENS FROM RAW LLM TEXT
 * 
 * Why This Exists:
 * External LLMs (Gemini / OpenAI) return captions and hashtags bundled together inside a single
 * continuous text string. This parser extracts the hashtags into an isolated array so the frontend
 * Post Studio can render individual interactive hashtag pill badges (with add/remove/delete capabilities)
 * while keeping the main caption textarea clean and unpolluted.
 * 
 * Features:
 * 1. Multilingual Support: Regex supports English alphanumeric, underscores, and Devanagari/Hindi (\u0900-\u097F) scripts (e.g. #दीपावली).
 * 2. Automatic Deduplication: Uses `new Set()` to strip any duplicate hashtags generated by the LLM.
 * 
 * @param {string} text - Raw output string received from LLM
 * @returns {Array<string>} Unique list of formatted hashtag strings (e.g. ['#DiwaliOffer', '#RealEstate'])
 */
export function extractHashtags(text = '') {
  if (!text || typeof text !== 'string') return [];

  // Match all hashtags starting with '#' followed by alphanumeric characters, underscores, or Hindi/Devanagari Unicode
  const matches = text.match(/#[a-zA-Z0-9_\u0900-\u097F]+/g) || [];

  // Convert Set back to array to guarantee unique hashtag tokens with zero duplicates
  return Array.from(new Set(matches));
}


/**
 * Build structured system and user prompt for external LLMs (Gemini / OpenAI)
 * Injects complete BrandKit identity for maximum relevance and conversion.
 *
 * @param {Object} context - Live BrandKit details
 * @param {Object} params - User request parameters
 * @returns {string} Formatted prompt string
 */
export function buildAiPrompt(context = {}, params = {}) {
  const fullLocation = [context.address, context.city, context.state, context.country]
    .filter(Boolean)
    .join(', ');

  return `You are an expert social media copywriter. Write a high-converting ${params.platform || 'INSTAGRAM'} caption in ${context.captionLanguage} with tone '${params.tone}'.

Business Context (from BrandKit):
- Business Name: '${context.businessName}'
- Business Category: '${context.categoryName}'
- Tagline: '${context.tagline}'
- Key USPs / Value Propositions: '${context.businessUsps}'
- Target Audience: '${context.targetAudience}'
- Location: '${fullLocation}'
- Working Hours: '${context.workingHours}'
- Contact: Phone '${context.phone}', WhatsApp '${context.whatsapp}', Email '${context.email}'
- Social Handles / Reviews: Instagram '${context.instagramHandle}', Facebook '${context.facebookHandle}', LinkedIn '${context.linkedinHandle}', Google Review Link '${context.gmbReviewUrl}'

Post Content Parameters:
- Topic / Event / Occasion: '${params.topic || params.festivalName || params.occasionName || 'Business Update'}'
- Offer / Discount: '${params.offerText || 'None'}'
- Custom Details: '${params.customText || ''}'

Format Requirements:
1. Catchy headline with relevant emojis.
2. Body text weaving in tagline, USPs, and offer details.
3. Clean Call-To-Action (CTA) with phone, WhatsApp, email, address, working hours, and social links as provided.
4. End with 8 to 12 targeted trending hashtags based on business name, category, city, state, topic, and platform.`;
}

/**
 * High-Performance Rule-Based AI Caption Synthesizer
 * Provides zero-config instantaneous fallback when external API quotas are exhausted or keys are unconfigured.
 *
 * @param {Object} context
 * @returns {{ captionText: string, hashtags: Array<string> }}
 */
export function synthesizeSmartCaption({
  businessName = 'Our Brand',
  tagline = '',
  categoryName = '',
  city = '',
  state = '',
  country = 'India',
  address = '',
  phone = '',
  whatsapp = '',
  email = '',
  instagramHandle = '',
  facebookHandle = '',
  linkedinHandle = '',
  targetAudience = '',
  businessUsps = '',
  workingHours = '',
  gmbReviewUrl = '',
  upiVpa = '',
  topic = '',
  festivalName = '',
  occasionName = '',
  customText = '',
  offerText = '',
  tone = 'PROMOTIONAL',
  language = 'ENGLISH',
  platform = 'INSTAGRAM',
}) {
  const isHinglish = language === 'HINGLISH';
  const isHindi = language === 'HINDI';

  const contextTitle = festivalName || occasionName || topic || 'Special Announcement';

  // Format location line
  const locationParts = [address, city, state, country && country !== 'India' ? country : ''].filter(Boolean);
  const locationStr = locationParts.join(', ');

  // Construct Contact & CTA Details
  const ctaParts = [];
  if (whatsapp) ctaParts.push(`📲 WhatsApp: ${whatsapp}`);
  if (phone && phone !== whatsapp) ctaParts.push(`📞 Call: ${phone}`);
  if (email) ctaParts.push(`✉️ Email: ${email}`);
  if (locationStr) ctaParts.push(`📍 Location: ${locationStr}`);
  if (workingHours) ctaParts.push(`⏰ Hours: ${workingHours}`);
  if (gmbReviewUrl) ctaParts.push(`⭐ Google Review: ${gmbReviewUrl}`);
  if (upiVpa) ctaParts.push(`💳 UPI Pay: ${upiVpa}`);

  // Social handles mention
  const handles = [
    instagramHandle ? `@${instagramHandle.replace('@', '')}` : '',
    facebookHandle ? `@${facebookHandle.replace('@', '')}` : '',
    linkedinHandle ? `@${linkedinHandle.replace('@', '')}` : '',
  ].filter(Boolean);

  if (handles.length > 0) {
    ctaParts.push(`🔗 Follow Us: ${handles.join(' | ')}`);
  }

  const callToAction =
    ctaParts.length > 0
      ? ctaParts.join('\n')
      : `📩 DM us or connect with ${businessName} for more details!`;

  let headline = '';
  let body = '';
  let closing = '';

  // Integrate Category & USPs
  const categoryContext = categoryName ? ` (${categoryName})` : '';
  const uspSection = businessUsps
    ? isHinglish
      ? `\n\n✨ Kyon chunein hume:\n${businessUsps}`
      : isHindi
      ? `\n\n✨ हमारी खासियत:\n${businessUsps}`
      : `\n\n✨ Why Choose Us:\n${businessUsps}`
    : '';

  // Tone Variations
  if (tone === 'FESTIVE') {
    if (isHinglish) {
      headline = `✨ ${contextTitle} ki dher saari shubhkaamnayein from ${businessName}${categoryContext}! 🪔🎉`;
      body = `${tagline ? `"${tagline}"\n\n` : ''}Iss paavan avsar par ${businessName} laye hain aapke liye sabse khas aur premium offerings.${uspSection}\n\n${
        offerText ? `🔥 Special Offer: ${offerText}!` : 'Apne doston aur family ke sath iss tyohar ko aur khas banayein.'
      }${customText ? `\n📌 ${customText}` : ''}`;
      closing = `🎉 Warmest festival greetings to our valued customers & community!`;
    } else if (isHindi) {
      headline = `✨ ${businessName}${categoryContext} की तरफ से ${contextTitle} की हार्दिक शुभकामनाएं! 🪔🎉`;
      body = `${tagline ? `"${tagline}"\n\n` : ''}इस पावन अवसर पर पाएं हमारे विशेष ऑफर्स।${uspSection}\n\n${
        offerText ? `🔥 विशेष छूट: ${offerText}!` : 'अपने परिवार के साथ इस त्यौहार को और भी खास बनाएं।'
      }${customText ? `\n📌 ${customText}` : ''}`;
      closing = `🎉 आप सभी को त्यौहार की बहुत-बहुत शुभकामनाएं!`;
    } else {
      headline = `✨ Warm wishes on ${contextTitle} from ${businessName}${categoryContext}! 🪔🎉`;
      body = `${tagline ? `"${tagline}"\n\n` : ''}Celebrate this festival season with our exclusive collection & special deals crafted just for you.${uspSection}\n\n${
        offerText ? `🎁 Special Offer: ${offerText}!` : 'Make this occasion unforgettable with your loved ones.'
      }${customText ? `\n📌 ${customText}` : ''}`;
      closing = `🎉 Best festival wishes to all our wonderful patrons!`;
    }
  } else if (tone === 'URGENT') {
    if (isHinglish) {
      headline = `🚨 HURRY! Limited Time Offer from ${businessName}${categoryContext}! ⏳💥`;
      body = `${tagline ? `"${tagline}"\n\n` : ''}Yeh offer zyada din nahi tikega! ${
        offerText ? `⚡ ${offerText}` : 'Aaj hi claim karein apna special discount.'
      }${uspSection}${customText ? `\n\n📌 Note: ${customText}` : ''}`;
      closing = `🔥 Stock/slots khatam hone se pehle abhi contact karein!`;
    } else {
      headline = `🚨 LIMITED TIME ONLY! Special Announcement from ${businessName}${categoryContext}! ⏳💥`;
      body = `${tagline ? `"${tagline}"\n\n` : ''}Don't miss out on this exclusive opportunity! ${
        offerText ? `⚡ ${offerText}` : 'Claim your deal before time runs out.'
      }${uspSection}${customText ? `\n\n📌 Details: ${customText}` : ''}`;
      closing = `🔥 Hurry up! Contact us today before this deal expires!`;
    }
  } else if (tone === 'WITTY') {
    headline = `😎 Looking for the best ${contextTitle}? ${businessName}${categoryContext} has got you covered! 🚀✨`;
    body = `${tagline ? `"${tagline}"\n\n` : ''}Why settle for ordinary when you can get top-notch quality with us?${uspSection}\n\n${
      offerText ? `💡 Bonus Deal: ${offerText}` : 'Treat yourself today because you deserve the best!'
    }${customText ? `\n📌 ${customText}` : ''}`;
    closing = `👉 Double tap if you agree and message us to get started!`;
  } else if (tone === 'PROFESSIONAL') {
    headline = `💼 Delivering Excellence & Trust | ${businessName}${categoryContext}`;
    body = `${tagline ? `"${tagline}"\n\n` : ''}At ${businessName}, we specialize in top-tier solutions for ${contextTitle}. Designed specifically for ${
      targetAudience || 'our valued clients'
    }.${uspSection}${
      offerText ? `\n\n⭐ Featured Offer: ${offerText}` : ''
    }${customText ? `\n\n📌 Details: ${customText}` : ''}`;
    closing = `🤝 Connect with our professional team today for personalized assistance.`;
  } else {
    // Default PROMOTIONAL / FRIENDLY
    if (isHinglish) {
      headline = `🌟 ${businessName}${categoryContext} me aapka swagat hai! 🎉`;
      body = `${tagline ? `"${tagline}"\n\n` : ''}Kya aap dhoondh rahe hain best ${contextTitle}? Hum laye hain aapke liye sabse behtareen quality.${uspSection}\n\n${
        offerText ? `🎉 Special Deal: ${offerText}` : ''
      }${customText ? `\n📌 ${customText}` : ''}`;
      closing = `👇 Comment below ya contact karein mazeedaar offers ke liye!`;
    } else {
      headline = `🌟 Elevate Your Experience with ${businessName}${categoryContext}! ✨`;
      body = `${tagline ? `"${tagline}"\n\n` : ''}Discover unmatched quality and premium offerings for ${contextTitle}.${uspSection}\n\n${
        offerText ? `🎁 Exclusive Deal: ${offerText}` : ''
      }${customText ? `\n📌 ${customText}` : ''}`;
      closing = `👉 Get in touch or visit us now to make the most of this offer!`;
    }
  }

  const captionText = `${headline}\n\n${body}\n\n${closing}\n\n${callToAction}`;

  // Generate Comprehensive Targeted Hashtags using ALL BrandKit context
  const baseTag = businessName.replace(/[^a-zA-Z0-9]/g, '');
  const categoryTag = categoryName ? categoryName.replace(/[^a-zA-Z0-9]/g, '') : '';
  const contextTag = contextTitle.replace(/[^a-zA-Z0-9]/g, '');
  const cityTag = city ? city.replace(/[^a-zA-Z0-9]/g, '') : '';
  const stateTag = state ? state.replace(/[^a-zA-Z0-9]/g, '') : '';

  const hashtagsSet = new Set([
    `#${baseTag}`,
    categoryTag ? `#${categoryTag}` : '#SmallBusiness',
    `#${contextTag}`,
    `#${contextTag}2026`,
    cityTag ? `#${cityTag}` : '',
    cityTag ? `#${cityTag}Business` : '',
    stateTag ? `#${stateTag}` : '',
    '#LocalBusiness',
    '#TrendingNow',
    '#SpecialOffer',
    '#QualityFirst',
    '#BrandFlowAI',
  ]);

  if (platform === 'INSTAGRAM') {
    hashtagsSet.add('#InstaDaily');
    hashtagsSet.add('#PostOfTheDay');
    hashtagsSet.add('#ExplorePage');
    hashtagsSet.add('#InstaGood');
  } else if (platform === 'LINKEDIN') {
    hashtagsSet.add('#Innovation');
    hashtagsSet.add('#BusinessGrowth');
    hashtagsSet.add('#Entrepreneurship');
    hashtagsSet.add('#Leadership');
  } else if (platform === 'FACEBOOK') {
    hashtagsSet.add('#FacebookPosts');
    hashtagsSet.add('#LocalServices');
  }

  const hashtags = Array.from(hashtagsSet).filter(Boolean);

  return {
    captionText,
    hashtags,
  };
}
