/**
 * Master Blueprint Definitions for 30 Premium Canva Vector Frames
 * Used by Admin Canva Builder to load & publish frames directly to Cloudinary.
 */
export const MASTER_FRAME_PRESETS = [
  // 1. Gold Luxury Border Frame
  {
    key: "GOLD_LUXURY",
    title: "Gold Luxury Border Frame",
    description: "Elegant golden transparent border overlay suitable for premium business posts.",
    elements: [
      {
        id: "shape_gold_bar",
        name: "Gold Capsule Footer",
        type: "CAPSULE",
        x: 140,
        y: 920,
        width: 800,
        height: 120,
        fillColor: "#EAB308",
        borderColor: "#FFFFFF",
        borderWidth: 3,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_gold_circle",
        name: "Headshot Circle",
        type: "CIRCLE",
        x: 160,
        y: 930,
        width: 100,
        height: 100,
        borderColor: "#EAB308",
        borderWidth: 4,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_gold_biz_name",
        name: "Business Name",
        type: "TEXT",
        x: 280,
        y: 940,
        width: 600,
        height: 40,
        fontSize: 26,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Sunrise Real Estate",
      },
      {
        id: "text_gold_phone",
        name: "Phone Number",
        type: "TEXT",
        x: 280,
        y: 980,
        width: 600,
        height: 35,
        fontSize: 20,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FEF08A",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 98765 43210",
      },
    ],
  },

  // 2. Classic Corporate Minimal Overlay
  {
    key: "CORPORATE_MINIMAL",
    title: "Classic Corporate Minimal Overlay",
    description: "Clean transparent footer and corner badge overlay for business announcements.",
    elements: [
      {
        id: "shape_corp_footer",
        name: "Corporate Footer",
        type: "RECTANGLE",
        x: 0,
        y: 940,
        width: 1080,
        height: 140,
        fillColor: "#0F172A",
        borderColor: "#38BDF8",
        borderWidth: 2,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_corp_circle",
        name: "Owner Photo",
        type: "CIRCLE",
        x: 40,
        y: 955,
        width: 110,
        height: 110,
        borderColor: "#38BDF8",
        borderWidth: 3,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_corp_biz_name",
        name: "Company Name",
        type: "TEXT",
        x: 180,
        y: 960,
        width: 500,
        height: 40,
        fontSize: 28,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Apex Financial Services",
      },
      {
        id: "text_corp_phone",
        name: "Contact Phone",
        type: "TEXT",
        x: 180,
        y: 1005,
        width: 400,
        height: 35,
        fontSize: 20,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#38BDF8",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 99999 88888",
      },
    ],
  },

  // 3. Royal Festive Garland Overlay
  {
    key: "ROYAL_FESTIVE",
    title: "Royal Festive Garland Overlay",
    description: "Traditional crimson and gold ornamental garland footer for Diwali, Dussehra & Eid.",
    elements: [
      {
        id: "shape_fest_bar",
        name: "Crimson Bar",
        type: "RECTANGLE",
        x: 0,
        y: 920,
        width: 1080,
        height: 160,
        fillColor: "#881337",
        borderColor: "#F59E0B",
        borderWidth: 3,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_fest_circle",
        name: "Festive Circle",
        type: "CIRCLE",
        x: 50,
        y: 935,
        width: 130,
        height: 130,
        borderColor: "#F59E0B",
        borderWidth: 4,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_fest_name",
        name: "Business Name",
        type: "TEXT",
        x: 210,
        y: 950,
        width: 550,
        height: 45,
        fontSize: 30,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FEF08A",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Royal Sweets & Bakery",
      },
      {
        id: "text_fest_phone",
        name: "Contact Phone",
        type: "TEXT",
        x: 210,
        y: 1000,
        width: 500,
        height: 35,
        fontSize: 22,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 98765 43210",
      },
    ],
  },

  // 4. Cyber Neon Tech Pill
  {
    key: "CYBER_NEON",
    title: "Cyber Neon Tech Pill",
    description: "Futuristic glowing neon cyan and violet rounded container for modern brands.",
    elements: [
      {
        id: "shape_neon_pill",
        name: "Neon Capsule",
        type: "CAPSULE",
        x: 60,
        y: 930,
        width: 960,
        height: 110,
        fillColor: "#1E1B4B",
        borderColor: "#06B6D4",
        borderWidth: 3,
        dynamicSlot: "NONE",
      },
      {
        id: "text_neon_title",
        name: "Brand Title",
        type: "TEXT",
        x: 100,
        y: 950,
        width: 500,
        height: 35,
        fontSize: 26,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#22D3EE",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Nexus Cyber Solutions",
      },
      {
        id: "text_neon_phone",
        name: "Contact",
        type: "TEXT",
        x: 620,
        y: 950,
        width: 360,
        height: 35,
        fontSize: 22,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#A7F3D0",
        textAlign: "right",
        dynamicSlot: "PHONE",
        text: "+91 91234 56789",
      },
    ],
  },

  // 5. Emerald Royale Premium Frame
  {
    key: "EMERALD_ROYALE",
    title: "Emerald Royale Premium Frame",
    description: "Deep emerald green with polished gold trim overlay for wealth & luxury brands.",
    elements: [
      {
        id: "shape_emerald_box",
        name: "Emerald Container",
        type: "RECTANGLE",
        x: 40,
        y: 920,
        width: 1000,
        height: 125,
        fillColor: "#064E3B",
        borderColor: "#F59E0B",
        borderWidth: 2,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_emerald_ring",
        name: "Advisor Ring",
        type: "CIRCLE",
        x: 70,
        y: 935,
        width: 95,
        height: 95,
        borderColor: "#F59E0B",
        borderWidth: 3,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_emerald_name",
        name: "Business Name",
        type: "TEXT",
        x: 190,
        y: 945,
        width: 550,
        height: 38,
        fontSize: 26,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Verdant Wealth Management",
      },
      {
        id: "text_emerald_phone",
        name: "Phone Number",
        type: "TEXT",
        x: 190,
        y: 988,
        width: 400,
        height: 32,
        fontSize: 19,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#6EE7B7",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 98888 77777",
      },
    ],
  },

  // 6. Frosted Glass Corner Card
  {
    key: "FROSTED_GLASS",
    title: "Frosted Glass Corner Card",
    description: "Modern glassmorphism translucent floating card anchored in bottom-left corner.",
    elements: [
      {
        id: "shape_glass_card",
        name: "Glass Card",
        type: "RECTANGLE",
        x: 40,
        y: 880,
        width: 600,
        height: 160,
        fillColor: "#1E293B",
        borderColor: "#94A3B8",
        borderWidth: 2,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_glass_circle",
        name: "Profile Ring",
        type: "CIRCLE",
        x: 65,
        y: 905,
        width: 110,
        height: 110,
        borderColor: "#38BDF8",
        borderWidth: 3,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_glass_name",
        name: "Business Name",
        type: "TEXT",
        x: 200,
        y: 920,
        width: 420,
        height: 40,
        fontSize: 24,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Studio Lumina Architecture",
      },
      {
        id: "text_glass_phone",
        name: "Contact Phone",
        type: "TEXT",
        x: 200,
        y: 970,
        width: 420,
        height: 35,
        fontSize: 20,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#7DD3FC",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 97777 66666",
      },
    ],
  },

  // 7. Gourmet Restaurant Banner
  {
    key: "GOURMET_CULINARY",
    title: "Gourmet Restaurant Banner",
    description: "Warm espresso and golden amber footer ribbon tailored for restaurants & cafes.",
    elements: [
      {
        id: "shape_gourmet_bar",
        name: "Espresso Ribbon",
        type: "RECTANGLE",
        x: 0,
        y: 920,
        width: 1080,
        height: 160,
        fillColor: "#451A03",
        borderColor: "#F59E0B",
        borderWidth: 2,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_gourmet_circle",
        name: "Chef Circle",
        type: "CIRCLE",
        x: 50,
        y: 935,
        width: 130,
        height: 130,
        borderColor: "#F59E0B",
        borderWidth: 4,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_gourmet_name",
        name: "Restaurant Name",
        type: "TEXT",
        x: 210,
        y: 950,
        width: 550,
        height: 45,
        fontSize: 30,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FDE68A",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Spice Route Bistro & Bar",
      },
      {
        id: "text_gourmet_phone",
        name: "Order Hotline",
        type: "TEXT",
        x: 210,
        y: 1000,
        width: 500,
        height: 35,
        fontSize: 22,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 94444 33333",
      },
    ],
  },

  // 8. Rose Gold Elegance Spa Frame
  {
    key: "ROSE_GOLD_SPA",
    title: "Rose Gold Elegance Spa Frame",
    description: "Soft rose gold accent arch for beauty parlors, salons, and wellness spas.",
    elements: [
      {
        id: "shape_spa_bar",
        name: "Rose Capsule",
        type: "CAPSULE",
        x: 100,
        y: 920,
        width: 880,
        height: 120,
        fillColor: "#831843",
        borderColor: "#F472B6",
        borderWidth: 2,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_spa_circle",
        name: "Stylist Circle",
        type: "CIRCLE",
        x: 130,
        y: 930,
        width: 100,
        height: 100,
        borderColor: "#F472B6",
        borderWidth: 3,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_spa_name",
        name: "Salon Name",
        type: "TEXT",
        x: 250,
        y: 945,
        width: 500,
        height: 40,
        fontSize: 26,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FCE7F3",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Glow Beauty Lounge & Spa",
      },
      {
        id: "text_spa_phone",
        name: "Appointment Phone",
        type: "TEXT",
        x: 250,
        y: 985,
        width: 450,
        height: 35,
        fontSize: 20,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 93333 22222",
      },
    ],
  },

  // 9. Prime Property Luxury Overlay
  {
    key: "REAL_ESTATE_PRIME",
    title: "Prime Property Luxury Overlay",
    description: "Split navy and gold bottom strip overlay for real estate brokers & property listings.",
    elements: [
      {
        id: "shape_re_bar",
        name: "Navy Gold Bar",
        type: "RECTANGLE",
        x: 0,
        y: 920,
        width: 1080,
        height: 160,
        fillColor: "#0F172A",
        borderColor: "#D97706",
        borderWidth: 3,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_re_circle",
        name: "Agent Headshot",
        type: "CIRCLE",
        x: 40,
        y: 935,
        width: 130,
        height: 130,
        borderColor: "#D97706",
        borderWidth: 4,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_re_name",
        name: "Agency Name",
        type: "TEXT",
        x: 200,
        y: 950,
        width: 550,
        height: 45,
        fontSize: 28,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FEF3C7",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Skyline Luxury Homes",
      },
      {
        id: "text_re_phone",
        name: "Agent Phone",
        type: "TEXT",
        x: 200,
        y: 1000,
        width: 500,
        height: 35,
        fontSize: 22,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 92222 11111",
      },
    ],
  },

  // 10. Voltage Athletic Gym Frame
  {
    key: "ATHLETIC_GYM",
    title: "Voltage Athletic Gym Frame",
    description: "High-contrast voltage yellow and dark charcoal overlay for gyms & fitness trainers.",
    elements: [
      {
        id: "shape_gym_bar",
        name: "Voltage Charcoal Bar",
        type: "RECTANGLE",
        x: 0,
        y: 930,
        width: 1080,
        height: 150,
        fillColor: "#18181B",
        borderColor: "#EAB308",
        borderWidth: 4,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_gym_circle",
        name: "Trainer Ring",
        type: "CIRCLE",
        x: 40,
        y: 945,
        width: 120,
        height: 120,
        borderColor: "#EAB308",
        borderWidth: 4,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_gym_name",
        name: "Gym Name",
        type: "TEXT",
        x: 190,
        y: 955,
        width: 550,
        height: 40,
        fontSize: 30,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FACC15",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Iron Core Fitness Club",
      },
      {
        id: "text_gym_phone",
        name: "Join Hotline",
        type: "TEXT",
        x: 190,
        y: 1005,
        width: 450,
        height: 35,
        fontSize: 22,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 91111 00000",
      },
    ],
  },

  // 11. MedCare Medical Professional Banner
  {
    key: "MEDCARE_CLINIC",
    title: "MedCare Medical Professional Banner",
    description: "Clean medical teal and white footer banner for clinics, doctors, & hospitals.",
    elements: [
      {
        id: "shape_med_bar",
        name: "Teal Container",
        type: "RECTANGLE",
        x: 0,
        y: 930,
        width: 1080,
        height: 150,
        fillColor: "#0F766E",
        borderColor: "#CCFBF1",
        borderWidth: 2,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_med_circle",
        name: "Doctor Ring",
        type: "CIRCLE",
        x: 40,
        y: 945,
        width: 120,
        height: 120,
        borderColor: "#FFFFFF",
        borderWidth: 4,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_med_name",
        name: "Clinic Name",
        type: "TEXT",
        x: 190,
        y: 955,
        width: 550,
        height: 40,
        fontSize: 28,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Dr. Sharma Super Care Clinic",
      },
      {
        id: "text_med_phone",
        name: "Emergency Phone",
        type: "TEXT",
        x: 190,
        y: 1005,
        width: 450,
        height: 35,
        fontSize: 20,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#CCFBF1",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 90000 12345",
      },
    ],
  },

  // 12. Diamond Platinum Royale Overlay
  {
    key: "JEWELLERY_DIAMOND",
    title: "Diamond Platinum Royale Overlay",
    description: "Platinum white and gold ornamental border overlay for luxury jewellery & fashion brands.",
    elements: [
      {
        id: "shape_jewel_bar",
        name: "Jewel Capsule",
        type: "CAPSULE",
        x: 100,
        y: 920,
        width: 880,
        height: 120,
        fillColor: "#1E1B4B",
        borderColor: "#F59E0B",
        borderWidth: 2,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_jewel_circle",
        name: "Logo Badge Ring",
        type: "CIRCLE",
        x: 130,
        y: 930,
        width: 100,
        height: 100,
        borderColor: "#F59E0B",
        borderWidth: 3,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_jewel_name",
        name: "Store Name",
        type: "TEXT",
        x: 250,
        y: 945,
        width: 500,
        height: 40,
        fontSize: 26,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FEF08A",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Ornate Gold & Diamonds",
      },
      {
        id: "text_jewel_phone",
        name: "Customer Helpline",
        type: "TEXT",
        x: 250,
        y: 985,
        width: 450,
        height: 35,
        fontSize: 20,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 98989 89898",
      },
    ],
  },

  // 13. Futuristic Tech Startup Pill Bar
  {
    key: "TECH_STARTUP",
    title: "Futuristic Tech Startup Pill Bar",
    description: "Indigo to violet gradient floating pill bar for tech platforms & agency posts.",
    elements: [
      {
        id: "shape_tech_bar",
        name: "Indigo Tech Pill",
        type: "CAPSULE",
        x: 80,
        y: 930,
        width: 920,
        height: 110,
        fillColor: "#312E81",
        borderColor: "#818CF8",
        borderWidth: 2,
        dynamicSlot: "NONE",
      },
      {
        id: "text_tech_name",
        name: "Company Name",
        type: "TEXT",
        x: 130,
        y: 950,
        width: 500,
        height: 35,
        fontSize: 26,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#C7D2FE",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "CloudScale AI Innovations",
      },
      {
        id: "text_tech_phone",
        name: "Contact",
        type: "TEXT",
        x: 640,
        y: 950,
        width: 320,
        height: 35,
        fontSize: 22,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "right",
        dynamicSlot: "PHONE",
        text: "+91 95555 44444",
      },
    ],
  },

  // 14. Ultra Minimal Soft Line Overlay
  {
    key: "MINIMAL_WHITE",
    title: "Ultra Minimal Soft Line Overlay",
    description: "Crisp clean white footer border overlay for modern minimalist creators & freelancers.",
    elements: [
      {
        id: "shape_min_footer",
        name: "Minimal Line",
        type: "RECTANGLE",
        x: 0,
        y: 950,
        width: 1080,
        height: 130,
        fillColor: "#020617",
        borderColor: "#E2E8F0",
        borderWidth: 1,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_min_circle",
        name: "Creator Avatar",
        type: "CIRCLE",
        x: 40,
        y: 960,
        width: 100,
        height: 100,
        borderColor: "#F8FAFC",
        borderWidth: 2,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_min_name",
        name: "Creator Name",
        type: "TEXT",
        x: 160,
        y: 970,
        width: 500,
        height: 35,
        fontSize: 26,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#F8FAFC",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Aria Chen Photography",
      },
      {
        id: "text_min_phone",
        name: "Contact Phone",
        type: "TEXT",
        x: 160,
        y: 1010,
        width: 400,
        height: 30,
        fontSize: 18,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#94A3B8",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 97777 00000",
      },
    ],
  },

  // 15. Traditional Mandala Cultural Frame
  {
    key: "MANDALA_CULTURAL",
    title: "Traditional Mandala Cultural Frame",
    description: "Marigold orange and gold mandala corner overlay for traditional Indian festivals & cultural events.",
    elements: [
      {
        id: "shape_mandala_bar",
        name: "Mandala Bar",
        type: "RECTANGLE",
        x: 0,
        y: 920,
        width: 1080,
        height: 160,
        fillColor: "#7C2D12",
        borderColor: "#F97316",
        borderWidth: 3,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_mandala_circle",
        name: "Store Owner Photo",
        type: "CIRCLE",
        x: 50,
        y: 935,
        width: 130,
        height: 130,
        borderColor: "#FB923C",
        borderWidth: 4,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_mandala_name",
        name: "Store Name",
        type: "TEXT",
        x: 210,
        y: 950,
        width: 550,
        height: 45,
        fontSize: 30,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FED7AA",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Heritage Silk & Crafts",
      },
      {
        id: "text_mandala_phone",
        name: "Contact Phone",
        type: "TEXT",
        x: 210,
        y: 1000,
        width: 500,
        height: 35,
        fontSize: 22,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 98888 12345",
      },
    ],
  },

  // 16. Automobile Showroom Showcase
  {
    key: "AUTOMOBILE_SHOWROOM",
    title: "Turbo Motors Luxury Showcase",
    description: "Metallic silver and crimson split accent container for auto dealerships & car launches.",
    elements: [
      {
        id: "shape_auto_footer",
        name: "Crimson Metallic Footer",
        type: "RECTANGLE",
        x: 0,
        y: 910,
        width: 1080,
        height: 170,
        fillColor: "#991B1B",
        borderColor: "#E2E8F0",
        borderWidth: 3,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_auto_circle",
        name: "Showroom Logo Circle",
        type: "CIRCLE",
        x: 45,
        y: 925,
        width: 140,
        height: 140,
        borderColor: "#FFFFFF",
        borderWidth: 5,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_auto_name",
        name: "Dealership Name",
        type: "TEXT",
        x: 215,
        y: 940,
        width: 550,
        height: 45,
        fontSize: 30,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Turbo Motors Luxury Hub",
      },
      {
        id: "text_auto_phone",
        name: "Test Drive Hotline",
        type: "TEXT",
        x: 215,
        y: 995,
        width: 500,
        height: 35,
        fontSize: 22,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FCA5A5",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 97777 99999",
      },
    ],
  },

  // 17. Political & Civic Campaign Frame
  {
    key: "POLITICAL_CAMPAIGN",
    title: "Electoral Pride & Public Service Frame",
    description: "Saffron and emerald tri-color ribbon footer for political leaders & public service campaigns.",
    elements: [
      {
        id: "shape_pol_footer",
        name: "Tri-Color Saffron Bar",
        type: "RECTANGLE",
        x: 0,
        y: 910,
        width: 1080,
        height: 170,
        fillColor: "#C2410C",
        borderColor: "#FACC15",
        borderWidth: 3,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_pol_circle",
        name: "Candidate Laurel Ring",
        type: "CIRCLE",
        x: 50,
        y: 925,
        width: 140,
        height: 140,
        borderColor: "#FACC15",
        borderWidth: 5,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_pol_name",
        name: "Leader Name",
        type: "TEXT",
        x: 220,
        y: 940,
        width: 600,
        height: 45,
        fontSize: 32,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Rajesh Kumar (Public Leader)",
      },
      {
        id: "text_pol_phone",
        name: "Campaign Helpline",
        type: "TEXT",
        x: 220,
        y: 995,
        width: 500,
        height: 35,
        fontSize: 22,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FEF08A",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 96666 55555",
      },
    ],
  },

  // 18. Education & Coaching Academy
  {
    key: "EDUCATION_ACADEMY",
    title: "Excellence Study & Skill Academy",
    description: "Deep navy and scholar gold footer for schools, coaching institutes & online academies.",
    elements: [
      {
        id: "shape_edu_bar",
        name: "Scholar Navy Bar",
        type: "RECTANGLE",
        x: 0,
        y: 930,
        width: 1080,
        height: 150,
        fillColor: "#1E3A8A",
        borderColor: "#F59E0B",
        borderWidth: 3,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_edu_circle",
        name: "Tutor Photo Ring",
        type: "CIRCLE",
        x: 40,
        y: 945,
        width: 120,
        height: 120,
        borderColor: "#F59E0B",
        borderWidth: 4,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_edu_name",
        name: "Institute Name",
        type: "TEXT",
        x: 190,
        y: 955,
        width: 550,
        height: 40,
        fontSize: 28,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Pinnacle IAS & Skill Academy",
      },
      {
        id: "text_edu_phone",
        name: "Admission Helpline",
        type: "TEXT",
        x: 190,
        y: 1005,
        width: 450,
        height: 35,
        fontSize: 20,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#93C5FD",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 94444 11111",
      },
    ],
  },

  // 19. Solitaire Diamond Jewellery Frame
  {
    key: "JEWELRY_DIAMOND_LUXURY",
    title: "Royal Solitaire Diamond Filigree",
    description: "Deep plum and filigree gold frame border for high-end solitaire & bridal jewellery.",
    elements: [
      {
        id: "shape_dia_bar",
        name: "Plum Filigree Bar",
        type: "RECTANGLE",
        x: 50,
        y: 910,
        width: 980,
        height: 140,
        fillColor: "#4C1D95",
        borderColor: "#F59E0B",
        borderWidth: 3,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_dia_circle",
        name: "Jeweller Logo",
        type: "CIRCLE",
        x: 80,
        y: 925,
        width: 110,
        height: 110,
        borderColor: "#F59E0B",
        borderWidth: 3,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_dia_name",
        name: "Store Name",
        type: "TEXT",
        x: 220,
        y: 938,
        width: 550,
        height: 40,
        fontSize: 28,
        fontFamily: "Cinzel",
        fontWeight: "bold",
        fontColor: "#FDE68A",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Eternia Solitaire Jewels",
      },
      {
        id: "text_dia_phone",
        name: "VVIP Hotline",
        type: "TEXT",
        x: 220,
        y: 988,
        width: 450,
        height: 35,
        fontSize: 20,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 98989 00000",
      },
    ],
  },

  // 20. High-Fashion Vogue Editorial
  {
    key: "FASHION_BOUTIQUE",
    title: "High-Fashion Vogue Editorial Strip",
    description: "Monochrome noir and champagne gold border strip for haute couture & fashion labels.",
    elements: [
      {
        id: "shape_fash_bar",
        name: "Monochrome Noir Strip",
        type: "RECTANGLE",
        x: 0,
        y: 940,
        width: 1080,
        height: 140,
        fillColor: "#000000",
        borderColor: "#D4AF37",
        borderWidth: 2,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_fash_circle",
        name: "Designer Avatar",
        type: "CIRCLE",
        x: 40,
        y: 955,
        width: 110,
        height: 110,
        borderColor: "#D4AF37",
        borderWidth: 3,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_fash_name",
        name: "Boutique Label",
        type: "TEXT",
        x: 180,
        y: 965,
        width: 500,
        height: 40,
        fontSize: 26,
        fontFamily: "Playfair Display",
        fontWeight: "bold",
        fontColor: "#F3E5AB",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Maison de Couture Label",
      },
      {
        id: "text_fash_phone",
        name: "Studio Contact",
        type: "TEXT",
        x: 180,
        y: 1010,
        width: 400,
        height: 30,
        fontSize: 18,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 93333 11111",
      },
    ],
  },

  // 21. Cyberpunk Gaming & Esports
  {
    key: "GAMING_ESPORTS",
    title: "Cyberpunk Gaming & Esports Capsule",
    description: "Electric purple & neon lime angled capsule pill for streamers & gaming teams.",
    elements: [
      {
        id: "shape_game_pill",
        name: "Neon Gamer Capsule",
        type: "CAPSULE",
        x: 60,
        y: 930,
        width: 960,
        height: 110,
        fillColor: "#581C87",
        borderColor: "#84CC16",
        borderWidth: 3,
        dynamicSlot: "NONE",
      },
      {
        id: "text_game_title",
        name: "Team Tag",
        type: "TEXT",
        x: 110,
        y: 950,
        width: 500,
        height: 35,
        fontSize: 28,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#BEF264",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Vortex Esports League",
      },
      {
        id: "text_game_phone",
        name: "Discord / Stream Handle",
        type: "TEXT",
        x: 630,
        y: 950,
        width: 350,
        height: 35,
        fontSize: 22,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "right",
        dynamicSlot: "PHONE",
        text: "Live @vortex_gaming",
      },
    ],
  },

  // 22. Happy Paws Vet Clinic
  {
    key: "PET_CARE_VET",
    title: "Happy Paws Vet & Pet Clinic",
    description: "Warm honey amber and teal paw accent container for pet clinics & grooming salons.",
    elements: [
      {
        id: "shape_pet_bar",
        name: "Teal Paw Footer",
        type: "RECTANGLE",
        x: 0,
        y: 930,
        width: 1080,
        height: 150,
        fillColor: "#115E59",
        borderColor: "#F59E0B",
        borderWidth: 3,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_pet_circle",
        name: "Vet Doctor Photo",
        type: "CIRCLE",
        x: 40,
        y: 945,
        width: 120,
        height: 120,
        borderColor: "#F59E0B",
        borderWidth: 4,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_pet_name",
        name: "Clinic Name",
        type: "TEXT",
        x: 190,
        y: 955,
        width: 550,
        height: 40,
        fontSize: 28,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FEF08A",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Happy Paws Pet Care Hospital",
      },
      {
        id: "text_pet_phone",
        name: "Emergency Vet Line",
        type: "TEXT",
        x: 190,
        y: 1005,
        width: 450,
        height: 35,
        fontSize: 20,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 92222 33333",
      },
    ],
  },

  // 23. Eco Organic Bio Store
  {
    key: "ECO_ORGANIC_STORE",
    title: "Earth Organic & Bio Store",
    description: "Forest green and sage eco leaf ribbon for organic foods & wellness stores.",
    elements: [
      {
        id: "shape_eco_bar",
        name: "Forest Green Bar",
        type: "RECTANGLE",
        x: 0,
        y: 920,
        width: 1080,
        height: 160,
        fillColor: "#14532D",
        borderColor: "#86EFAC",
        borderWidth: 2,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_eco_circle",
        name: "Eco Badge Ring",
        type: "CIRCLE",
        x: 45,
        y: 935,
        width: 130,
        height: 130,
        borderColor: "#86EFAC",
        borderWidth: 4,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_eco_name",
        name: "Store Name",
        type: "TEXT",
        x: 200,
        y: 950,
        width: 550,
        height: 45,
        fontSize: 30,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#DCFCE7",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Fresh Earth Organic Superstore",
      },
      {
        id: "text_eco_phone",
        name: "Delivery WhatsApp",
        type: "TEXT",
        x: 200,
        y: 1000,
        width: 500,
        height: 35,
        fontSize: 22,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 91111 22222",
      },
    ],
  },

  // 24. Crypto & Web3 Fintech Frame
  {
    key: "FINTECH_CRYPTO",
    title: "Blockchain & Modern Wealth Pill",
    description: "Dark charcoal & electric cyan gradient pill for fintech apps & crypto platforms.",
    elements: [
      {
        id: "shape_crypto_pill",
        name: "Cyan Crypto Pill",
        type: "CAPSULE",
        x: 80,
        y: 930,
        width: 920,
        height: 110,
        fillColor: "#0F172A",
        borderColor: "#38BDF8",
        borderWidth: 3,
        dynamicSlot: "NONE",
      },
      {
        id: "text_crypto_name",
        name: "Platform Name",
        type: "TEXT",
        x: 130,
        y: 950,
        width: 500,
        height: 35,
        fontSize: 26,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#38BDF8",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Zenith Pay Fintech Hub",
      },
      {
        id: "text_crypto_phone",
        name: "Support Line",
        type: "TEXT",
        x: 640,
        y: 950,
        width: 320,
        height: 35,
        fontSize: 22,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "right",
        dynamicSlot: "PHONE",
        text: "+91 90000 90000",
      },
    ],
  },

  // 25. Wedding & Marriage Planner
  {
    key: "WEDDING_PLANNER",
    title: "Eternia Royal Marriage Banner",
    description: "Blush pink and vintage gold floral ribbon for wedding planners & banquet halls.",
    elements: [
      {
        id: "shape_wed_bar",
        name: "Blush Ribbon",
        type: "RECTANGLE",
        x: 0,
        y: 920,
        width: 1080,
        height: 160,
        fillColor: "#831843",
        borderColor: "#F59E0B",
        borderWidth: 3,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_wed_circle",
        name: "Planner Ring",
        type: "CIRCLE",
        x: 50,
        y: 935,
        width: 130,
        height: 130,
        borderColor: "#F59E0B",
        borderWidth: 4,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_wed_name",
        name: "Company Name",
        type: "TEXT",
        x: 210,
        y: 950,
        width: 550,
        height: 45,
        fontSize: 30,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FDE68A",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Royal Event & Wedding Planners",
      },
      {
        id: "text_wed_phone",
        name: "Booking Hotline",
        type: "TEXT",
        x: 210,
        y: 1000,
        width: 500,
        height: 35,
        fontSize: 22,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 98888 99999",
      },
    ],
  },

  // 26. Sweet Craving Pastry Studio
  {
    key: "BAKERY_CONFECTIONERY",
    title: "Sweet Craving Pastry Studio Pill",
    description: "Warm chocolate and berry pink pill for cake shops & home bakers.",
    elements: [
      {
        id: "shape_bake_pill",
        name: "Chocolate Pill",
        type: "CAPSULE",
        x: 100,
        y: 920,
        width: 880,
        height: 120,
        fillColor: "#451A03",
        borderColor: "#EC4899",
        borderWidth: 2,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_bake_circle",
        name: "Chef Ring",
        type: "CIRCLE",
        x: 130,
        y: 930,
        width: 100,
        height: 100,
        borderColor: "#EC4899",
        borderWidth: 3,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_bake_name",
        name: "Bakery Name",
        type: "TEXT",
        x: 250,
        y: 945,
        width: 500,
        height: 40,
        fontSize: 26,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FBCFE8",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Sweet Cravings Artisanal Bakery",
      },
      {
        id: "text_bake_phone",
        name: "Cake Order Phone",
        type: "TEXT",
        x: 250,
        y: 985,
        width: 450,
        height: 35,
        fontSize: 20,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 97777 44444",
      },
    ],
  },

  // 27. Live Stage DJ Concert
  {
    key: "MUSIC_CONCERT_FEST",
    title: "Live Stage Beats & DJ Event Banner",
    description: "Electric magenta and dark violet angled banner for concerts & DJ night events.",
    elements: [
      {
        id: "shape_music_bar",
        name: "Magenta Stage Bar",
        type: "RECTANGLE",
        x: 0,
        y: 920,
        width: 1080,
        height: 160,
        fillColor: "#701A75",
        borderColor: "#F43F5E",
        borderWidth: 3,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_music_circle",
        name: "DJ Photo Circle",
        type: "CIRCLE",
        x: 50,
        y: 935,
        width: 130,
        height: 130,
        borderColor: "#F43F5E",
        borderWidth: 4,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_music_name",
        name: "Event Title",
        type: "TEXT",
        x: 210,
        y: 950,
        width: 550,
        height: 45,
        fontSize: 30,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FECDD3",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Sunburn Beats Live Concert",
      },
      {
        id: "text_music_phone",
        name: "Ticket Line",
        type: "TEXT",
        x: 210,
        y: 1000,
        width: 500,
        height: 35,
        fontSize: 22,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 96666 11111",
      },
    ],
  },

  // 28. Construction Builders Industrial Frame
  {
    key: "CONSTRUCTION_BUILDERS",
    title: "Heavy Structural Infra Frame",
    description: "Safety yellow and industrial black striped border bar for builders & civil engineers.",
    elements: [
      {
        id: "shape_build_bar",
        name: "Industrial Bar",
        type: "RECTANGLE",
        x: 0,
        y: 930,
        width: 1080,
        height: 150,
        fillColor: "#09090B",
        borderColor: "#EAB308",
        borderWidth: 4,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_build_circle",
        name: "Engineer Ring",
        type: "CIRCLE",
        x: 40,
        y: 945,
        width: 120,
        height: 120,
        borderColor: "#EAB308",
        borderWidth: 4,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_build_name",
        name: "Company Name",
        type: "TEXT",
        x: 190,
        y: 955,
        width: 550,
        height: 40,
        fontSize: 28,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FACC15",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Titan Infra & Construction",
      },
      {
        id: "text_build_phone",
        name: "Office Contact",
        type: "TEXT",
        x: 190,
        y: 1005,
        width: 450,
        height: 35,
        fontSize: 20,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 95555 88888",
      },
    ],
  },

  // 29. SunPower Green Solar Energy
  {
    key: "SOLAR_CLEAN_ENERGY",
    title: "SunPower Green Tech Solar Pill",
    description: "Solar gold and emerald sky capsule pill for green energy & solar panel installers.",
    elements: [
      {
        id: "shape_solar_pill",
        name: "Solar Capsule",
        type: "CAPSULE",
        x: 80,
        y: 930,
        width: 920,
        height: 110,
        fillColor: "#065F46",
        borderColor: "#FACC15",
        borderWidth: 3,
        dynamicSlot: "NONE",
      },
      {
        id: "text_solar_name",
        name: "Brand Name",
        type: "TEXT",
        x: 130,
        y: 950,
        width: 500,
        height: 35,
        fontSize: 26,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FACC15",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "SunPower Green Tech Energy",
      },
      {
        id: "text_solar_phone",
        name: "Free Quote Hotline",
        type: "TEXT",
        x: 640,
        y: 950,
        width: 320,
        height: 35,
        fontSize: 22,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "right",
        dynamicSlot: "PHONE",
        text: "+91 94444 77777",
      },
    ],
  },

  // 30. Modernist Interior Design Studio
  {
    key: "INTERIOR_DESIGN",
    title: "Modernist Habitat Interiors Frame",
    description: "Warm terracotta and sandstone minimal card for interior designers & home decor.",
    elements: [
      {
        id: "shape_int_card",
        name: "Terracotta Container",
        type: "RECTANGLE",
        x: 40,
        y: 880,
        width: 600,
        height: 160,
        fillColor: "#7C2D12",
        borderColor: "#FED7AA",
        borderWidth: 2,
        dynamicSlot: "NONE",
      },
      {
        id: "avatar_int_circle",
        name: "Designer Headshot",
        type: "CIRCLE",
        x: 65,
        y: 905,
        width: 110,
        height: 110,
        borderColor: "#FED7AA",
        borderWidth: 3,
        dynamicSlot: "AVATAR_CIRCLE",
      },
      {
        id: "text_int_name",
        name: "Studio Name",
        type: "TEXT",
        x: 200,
        y: 920,
        width: 420,
        height: 40,
        fontSize: 24,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FFFFFF",
        textAlign: "left",
        dynamicSlot: "BUSINESS_NAME",
        text: "Habitat Modernist Interiors",
      },
      {
        id: "text_int_phone",
        name: "Consultation Phone",
        type: "TEXT",
        x: 200,
        y: 970,
        width: 420,
        height: 35,
        fontSize: 20,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        fontColor: "#FED7AA",
        textAlign: "left",
        dynamicSlot: "PHONE",
        text: "+91 93333 55555",
      },
    ],
  },
];
