-- AlterTable
ALTER TABLE "DesignStyle" ADD COLUMN IF NOT EXISTS "accentColor" TEXT NOT NULL DEFAULT '#EC4899',
ADD COLUMN IF NOT EXISTS "backgroundColor" TEXT NOT NULL DEFAULT '#0B0F17',
ADD COLUMN IF NOT EXISTS "colors" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "fontBody" TEXT NOT NULL DEFAULT 'Plus Jakarta Sans',
ADD COLUMN IF NOT EXISTS "fontHeader" TEXT NOT NULL DEFAULT 'Space Grotesk',
ADD COLUMN IF NOT EXISTS "gradient" TEXT,
ADD COLUMN IF NOT EXISTS "primaryColor" TEXT NOT NULL DEFAULT '#F59E0B',
ADD COLUMN IF NOT EXISTS "secondaryColor" TEXT NOT NULL DEFAULT '#0D9488';
